import 'package:flutter/material.dart';

const unselectedIconColor = Color(0xffC0C0C0);
const selectedIconColor = Color(0xff9296FF);
const floatingButtonColor = Color(0xff9296FF);
const kGrey = Color(0xff999999);
const scaffoldBackgroundColor = Color(0xffFBFBFD);
const progressBarBackgroundColor = Color(0xffF7F5FF);
const progressBarColor = Color(0xffC2EA93);
const circleAvatarColor = Color(0xffFFC276);
const circleAvatarBackColor = Color(0xffF6F6FC);
const kWhite = Colors.white;
const checkBoxBorderColor = Color(0xffBDC1FD);
const checkBoxFillColor = Color(0xff9296FF);
const kBlack = Colors.black;
const homeTextColor = Color(0xff979799);
const containerColor1 = Color(0xffFFC276);
const containerColor2 = Color(0xff9296FF);
const containerColor3 = Color(0xffC2EA93);
const containerColor4 = Color(0xffFF7649);
const indicatorColor1 = Color(0xff9296FF);
const indicatorColor2 = Color(0xffC2EA93);
const indicatorColor3 = Color(0xffFABE75);
const containerCircleColor1 = Color(0xffFF996D);
const containerStackColor2 = Color(0xff797FFF);
const containerStackColor3 = Color(0xffB2D986);
